### ISSUE TITLE
IDEA: Use fst package for loading Cache will boost startup performance

### ISSUE THREAD

**Issue by Fpadt** [KentonWhite/ProjectTemplate#191]
Dear All,

Who knows how I can get the **fst package** and it functionality build in the ProjectTemplate functionality

I recently discovered the fst Package [fst package](http://blog.revolutionanalytics.com/2017/02/fst-fast-serialization-of-r-data-frames.html ) 
Would like to use this feature for loading the Cache of ProjectTemplate and Cache each standard file as fst based upon config setting

So in case the same file is in the cache with fst extension and the file is just as old or newer this should be loaded.
In case it is older the system should load the normal file and directly save it as .fst

This does the trick

`
      load_dt <-
        function(pDATA_TABLE, pPATH = PATH_DATA) {

        file_time_format <- "%Y-%m-%d %H:%M:%S"
 
        # if fst version exists load it when it is more recent else load normal .RData file
      if (file.exists(file_fst) &
          strptime(file.mtime(file_fst)  , format = file_time_format) >=
          strptime(file.mtime(file_RData), format = file_time_format)) {
        assign(pDATA_TABLE,
               read.fst(path = file_fst, as.data.table = TRUE),
               envir = .GlobalEnv)
      } else {
        load(file_RData,  envir = .GlobalEnv)
        write.fst(get(pDATA_TABLE), file_fst)
      }
     
      # return()
    }`

**Comment by connectedblue** [comment]
Hi @Fpadt 

Have you synced with the latest version on github rather than `CRAN`?  There are a number of changes to caching which try and handle things in a smarter way (like only re-caching is something has changed for example to save speed).

It doesn't use `fst`, just the normal `RDS` format.  There could be some portability and speed benefits from migrating to `fst`.

**Comment by Fpadt** [comment]
thanks will sync maybe I have an old vesion. build somehting my slef using fst and quite happy

**Comment by KentonWhite** [comment]
OK -- closing this issue and it is referenced in #225.
