### ISSUE TITLE
.RProj creation

### ISSUE THREAD

**Issue by rsangole** [KentonWhite/ProjectTemplate#201]
I'm requesting a feature in the `create.project()` function that also creates a ProjectName.RProj file (and associated files) to the root folder?

I use ProjectTemplate reguarly now with RStudio, but since the function doesn't create a .RProj itself, it's a two step process for me today - i. Call create.project, and ii. Create a new R project within existing directory.

The advantage of making the work an RStudio project is 
1. Project specific configurations like Code Editing controls, Build tools controls, Git/SVN controls etc
2. RStudio functionality for loading a new project using the dropdown menu on the top right hand side

**Comment by KentonWhite** [comment]
@rsangole This sounds like a very nice feature.  I don't use RStudio personally but do know that many of our users do.  I'm not super familiar with how the .RProj file is supposed to look.  Could you start a pull request with a new folder `inst/defaults/rstudio` that is a copy of `inst/defaults/full` and then place in that folder the .RProj file you would like and where it should be in the directory structure.  We can then modify `create.project()` so that it takes a rstudio flag.

**Comment by rsangole** [comment]
Will do, cheers!

**Comment by rsangole** [comment]
Sent you an email, cheers.

**Comment by rsangole** [comment]
Hello, following up on this request; lost track of time. (But, the feature is still really useful!)

**Comment by Hugovdberg** [comment]
Could this be solved by pr #206? Perhaps it should be amended to rename the
.rproj file if it exists in the template. Rstudio will always show the
directory name as the project name so it isn't technically necessary to
rename the file.

Op 27 nov. 2017 05:53 schreef "Rahul S" <notifications@github.com>:

**Comment by rsangole** [comment]
Yea, I don't see why not. We can create a default template which hosts a basic .RProj file, and write a small function to rename it to the project name. Fits well within #206 framework.

**Comment by Hugovdberg** [comment]
I would suggest not to add another builtin template but either leave it up to the user to create his or her own custom template if an .Rproj file is necessary, or always add the .Rproj to the `full` template. The main advantage of putting it in the custom template is that we avoid discussions on whether we want 2, 4 or 8 spaces by default, want to add a new line at the end of the file if it's missing, remove spaces or not..

**Comment by rsangole** [comment]
That's fair, and it solves the problem at hand.
