### ISSUE TITLE
Feature Req - Projects, Wiki

### ISSUE THREAD

**Issue by rsangole** [KentonWhite/ProjectTemplate#220]
#### Report an Issue / Request a Feature

I'm submitting a (Check one with "x") : 
- [ ] bug report 
- [x] feature request

***

##### Issue Severity Classification - 

(Check one with "x") : 
- [ ] 1 - Severe
- [ ] 2 - Moderate
- [x] 3 - Low

Creators, 

Could you enable the creation of "projects", "tasks", and "wikis"? We have quite a few issues open which are feature requests, and there are a good number of ideas on where to go. It would help organize the work and track it to completion using these features. I would be happy lead this effort if I'm given the authority to do so; organize these tabs and keep them up to date.

**Comment by Hugovdberg** [comment]
As far as I know it isn't possible to allow creating projects without giving write permissions to the repository. I think it would be more useful to ask for a specific project. 
For example, I was working on a proposal to convert `ProjectTemplate` to the `tidyverse`, which could definitely benefit from a project to organise all the different tasks that need to be done for the conversion (and then I closed the wrong tab in my browser :-( ).

**Comment by rsangole** [comment]
Well, I was thinking even from the point of view of the organization of to-dos, the issues, and their status. For ex, as done in this repo. I'm not sure how to navigate the permission space though, if that's a concern.

When you say convert `ProjectTemplate` to `tidyverse`, do you mean convert all the internal functions to those from the `tidyverse`?

**Comment by Hugovdberg** [comment]
That's what I was thinking about, but I'll write the proposal from scratch in a new issue.

**Comment by rsangole** [comment]
@KentonWhite @johnmyleswhite When you get some time, could you look into creating a "project" structure we could work in? Something like [this ](https://github.com/glue-viz/glue/projects/3)or [this](https://github.com/rsangole/tidyrabbit/projects/1) (or perhaps try enabling it for a few of us?)

@Hugovdberg Sounds good. Let's collaborate and get this done.

**Comment by KentonWhite** [comment]
@rsangole Will try to look at it this weekend.

**Comment by KentonWhite** [comment]
Sorry been away.  I've created a basic project using the Kanban template.  Can add additional cards if you wish.  I didn't enable automation.  Let me know what tweaks you would like here.

**Comment by rsangole** [comment]
@KentonWhite Thanks for looking into this & creating the board. Looks like it's restricted for editing for us collaborators. Could you open that up in any way?

**Comment by KentonWhite** [comment]
At the moment this is a problem.  I'm asking if I can transfer project ownership to myself.  If that happens I should be able to provide access to the ProjectBoards.

**Comment by rsangole** [comment]
@KentonWhite OK. If you can do so, I'll be happy to contribute on the boards and help manage some of the new feature implementations.

**Comment by KentonWhite** [comment]
I've sent collaborator invites.  This should give access to the project boards & wikis.  Please let me know if it doesn't.
