### ISSUE TITLE
Support .rds files in data folder

### ISSUE THREAD

**Issue by eribul** [KentonWhite/ProjectTemplate#223]
#### Report an Issue / Request a Feature

I'm submitting a (Check one with "x") : 
- [ ] bug report 
- [x] feature request

***

##### Issue Severity Classification - 

(Check one with "x") : 
- [ ] 1 - Severe
- [ ] 2 - Moderate
- [x] 3 - Low

##### Expected Behavior

Possibility to use RDS files in .files-files for data

##### Current Behavior
```
Autoloading data
 Loading data set: data.with.ae
Error in do.call(extensions.dispatch.table[[file.type]], list(data.file,  : 
  'what' must be a function or character string
```
Also
```
ls(ProjectTemplate:::extensions.dispatch.table)
```
shows that RDS-files are not supported.

##### Steps to Reproduce Behavior

Save a .file with reference to RDS-file in the data catalog. Then `load.project`.

##### Version Information

R 3.4.3
ProjectTemplate: 0.8

**Comment by Hugovdberg** [comment]
This issue can be closed since the pull request was merged
