### ISSUE TITLE
Checking fails with current dev version of RSQLite

### ISSUE THREAD

**Issue by krlmlr** [KentonWhite/ProjectTemplate#228]
#### Report an Issue / Request a Feature

I'm submitting a (Check one with "x") : 
- [x] bug report 
- [ ] feature request

***

##### Issue Severity Classification - 

(Check one with "x") : 
- [ ] 1 - Severe
- [ ] 2 - Moderate
- [x] 3 - Low

##### Expected Behavior

`R CMD check` succeeds with the dev version of *RSQLite*.

##### Current Behavior

Doesn't, fails with:

```
      Warnings: 0
      Skipped:  0
      ── 1. Failure: ignored data files are not loaded (@test-load.R#183)  ───────────
      `load.project(override.config = list(data_ignore = ""))` threw an error with unexpected message.
      Expected match: "file is encrypted or is not a database"
      Actual message: "file is not a database"

      ══ testthat results  ═══════════════════════════════════════════════════════════
      OK: 636 SKIPPED: 4 FAILED: 1
      1. Failure: ignored data files are not loaded (@test-load.R#183)

      Error: testthat unit tests failed
      In addition: Warning message:
      call dbDisconnect() when finished working with a connection
      Execution halted
```

##### Steps to Reproduce Behavior

- Install `r-dbi/RSQLite` from GitHub
- Run `R CMD check` on *ProjectTemplate*

 
##### Version Information

*ProjectTemplate* 0.8, r-dbi/RSQLite@b9df7dd

##### Possible Solution

Please refrain from checking (exact) wording for third-party error messages.

**Comment by krlmlr** [comment]
RSQLite has been updated on CRAN, checks for ProjectTemplate fail now.

**Comment by KentonWhite** [comment]
Fixed and being submitted to CRAN
