### ISSUE TITLE
neither want to use data.table nor tibble. Can I turn both off?

### ISSUE THREAD

**Issue by AljoLe** [KentonWhite/ProjectTemplate#235]
#### Report an Issue / Request a Feature

I'm submitting a (Check one with "x") : 
- [ ] bug report 
- [x] feature request

***

##### Issue Severity Classification - 

(Check one with "x") : 
- [ ] 1 - Severe
- [ ] 2 - Moderate
- [x] 3 - Low

##### Expected Behavior
I want to choose which data frame should be transformed to a tibble

##### Current Behavior
Every dataframe is transformed to a tibble

##### Steps to Reproduce Behavior
Load the project

`library(ProjectTemplate); load.project()`

 
##### Possible Solution
make it possible to turn data.table- and tibble-conversion off

**Comment by Hugovdberg** [comment]
Currently it is not possible to disable the conversion to `tibble`. It was actually a conscious decision to implement it this way. The whole idea of `ProjectTemplate` is to build a framework that provides sensible defaults, with limited configuration possibilities (convention over configuration). I'm under the impression that the majority of people will not run into this issue you experience, and to paraphrase Hadley Wickham, if the row names actually tell something about the data it should be a normal column.

I would suggest that for this very specific use case you include a munge script that converts the data back to a normal dataframe.

**Comment by AljoLe** [comment]
I agree with you and Hadley Wickham on the rowname issue, unfortunately the bioconductor packages didn´t hav this in mind. Maybe in the future.
Than I will add this mungescript as you suggest it.

Best regards

**Comment by Hugovdberg** [comment]
That's rather unfortunate indeed, let's hope the bioconductor people will fix this for you ;-) closing this issue for now.
