### ISSUE TITLE
Feature request: Add feather reader

### ISSUE THREAD

**Issue by Hugovdberg** [KentonWhite/ProjectTemplate#237]
#### Report an Issue / Request a Feature

I'm submitting a (Check one with "x") : 
- feature request

***

##### Issue Severity Classification - 

(Check one with "x") : 
- 3 - Low

##### Expected Behavior

`.feather` files in the `data/` directory are loaded in memory.

##### Current Behavior

`.feather` files are ignored.

##### Possible Solution

```r
feather.reader <- function(data.file, filename, variable.name) {
    assign(variable.name, feather::read_feather(filename), envir = .TargetEnv)
}
```

**Comment by rsangole** [comment]
@Hugovdberg , any reason why we don't want to read feather files from `cache/`, or is it that conceptually, the "reader" functionality is being defined for the `data/` folder?

**Comment by KentonWhite** [comment]
This is just setting on the `feather` reader.  The cache feature is still being developed!

**Comment by rsangole** [comment]
Got it, thanks!
