### ISSUE TITLE
Q: How does one update the website?

### ISSUE THREAD

**Issue by rsangole** [KentonWhite/ProjectTemplate#242]
##### Issue Severity Classification - 

(Check one with "x") : 
- [ ] 1 - Severe
- [X] 2 - Moderate
- [ ] 3 - Low

What are the steps to update the website when we add a feature to this package?

**Comment by rsangole** [comment]
Found the material under /docs/.

**Comment by Hugovdberg** [comment]
The `docs/` directory is automatically recognised by GitHub pages for the public website, that's also the reason we renamed the `doc/` directory to `docs/` about a year ago. If you upload your project on GitHub you can use the directory directly for your public documentation.
