### ISSUE TITLE
Internal - Complete COC & License

### ISSUE THREAD

**Issue by rsangole** [KentonWhite/ProjectTemplate#245]
#### Report an Issue / Request a Feature

I'm submitting a (Check one with "x") : 
- [ ] bug report 
- [x] feature request

***

##### Issue Severity Classification - 

(Check one with "x") : 
- [ ] 1 - Severe
- [ ] 2 - Moderate
- [x] 3 - Low

In the interest of completeness, I noticed that the project is missing two items listed <[here](https://github.com/KentonWhite/ProjectTemplate/community)>.

@KentonWhite I didn't want to select the license since you own the project, but perhaps an MIT license makes sense for this project? As for the code of conduct, the default template seems quite good too.

Thoughts?

**Comment by KentonWhite** [comment]
I would follow the tidyverse lead.  What license are they using?

**Comment by rsangole** [comment]
tidyverse uses GNU General Public License

**Comment by KentonWhite** [comment]
I'm fine with the Tidyverse code of conduct.  Thanks @rsangole for asking!
