### ISSUE TITLE
Broken github link on ProjectTemplate website

### ISSUE THREAD

**Issue by nate-d-olson** [KentonWhite/ProjectTemplate#246]
#### Report an Issue / Request a Feature

I'm submitting a (Check one with "x") : 
- [ x] bug report 
- [ ] feature request

***

##### Issue Severity Classification - 

(Check one with "x") : 
- [ ] 1 - Severe
- [ ] 2 - Moderate
- [ x] 3 - Low

##### Expected Behavior
Github icon links to https://github.com/kentonswhite/ProjectTemplate.

##### Current Behavior
Github icon should link to https://github.com/KentonWhite/ProjectTemplate. 

##### Steps to Reproduce Behavior
Click on github icon at top of page from http://projecttemplate.net/.

**Comment by Hugovdberg** [comment]
I made a fix for the broken link, it will be merged soon. Thanks for noticing!
