### ISSUE TITLE
Question - install from github

### ISSUE THREAD

**Issue by rsangole** [KentonWhite/ProjectTemplate#257]
#### Report an Issue / Request a Feature

I'm submitting a (Check one with "x") : 
- [ ] bug report 
- [ ] feature request

***

##### Issue Severity Classification - 

(Check one with "x") : 
- [ ] 1 - Severe
- [ ] 2 - Moderate
- [x] 3 - Low

On the home page, the github install is

    install_github('johnmyleswhite/ProjectTemplate')

Yet, right now, we are in the package 'kentonwhite/projecttemplate'.

How does this work? I'm a bit confused.

**Comment by KentonWhite** [comment]
Its changed.  Thanks for seeing that!
