### ISSUE TITLE
Check and install missing packages on load.project()

### ISSUE THREAD

**Issue by sdrakulich** [KentonWhite/ProjectTemplate#259]
#### Report an Issue / Request a Feature

I'm submitting a (Check one with "x") : 
- [ ] bug report 
- [X ] feature request

***

##### Issue Severity Classification - 

(Check one with "x") : 
- [ ] 1 - Severe
- [ ] 2 - Moderate
- [X ] 3 - Low

##### Expected Behavior

A repository I move between systems works seamlessly when load.project() is executed.

##### Current Behavior

It fails to load packages the other system does not have installed.

##### Version Information

Latest version

##### Possible Solution

I would if I wasn't a complete beginner. Haven't touched the innards of a function yet.
That being said, I found this and felt it should be fairly straightforward to implement. I might try myself!
The package is called "pacman". [Explained here.](https://stackoverflow.com/a/19873732/9625673)

**Comment by Hugovdberg** [comment]
Hmm, I just noticed that all warnings generated inside `require.package` are currently hidden. Perhaps @KentonWhite can shine a light on why he coded it that way, it might be that it obscures the problem @sdrakulich experiences.

**Comment by sdrakulich** [comment]
First, I apologize for not using search.

Now that that's out of the way, I think I know what the problem is. The way I'm executing, there is no default repository set. If I could pass that argument globally to just default to the CRAN one, that should make this work under my infrastructure (Atom-editor with R-enabled functionality through jupyter lab).

**Comment by Hugovdberg** [comment]
Ah, but you don't get the request to select a repository? And do you get that request when manually installing a package? Because if that request is somehow hidden as an effect of using `require.package` as a wrapper around `install.packages` then we should try and fix that of course.

**Comment by sdrakulich** [comment]
Can I just reply to the email?
Anyways, this is the error I get. I'm missing the last package in my load
sequence.

Project name: XXX
> Loading project configuration
> Autoloading packages
>  Loading package: <<all my packages>>
>  Loading package: beepr
> Loading required package: beepr
> Error in contrib.url(repos, "source"): trying to use CRAN without setting
> a mirror
> Traceback:
>
> 1. load.project()
> 2. .load.libraries(config, my.project.info)
> 3. require.package(package.to.load)
> 4. install.packages(package.name)
> 5. contrib.url(repos, "source")
> 6. stop("trying to use CRAN without setting a mirror")
>

On Sat, May 5, 2018 at 11:06 AM, Hugo van den Berg <notifications@github.com

**Comment by KentonWhite** [comment]
We can unquiet warnings in `require.package`.  It was added to minimize the amount of information when installing packages.  It may be helpful for debugging.  I'll make a quick PR.

**Comment by KentonWhite** [comment]
Warnings are unquieted in `require.package`.

@sdrakulich can you reinstall `ProjectTemplate` from GitHub using `install_github('KentonWhite/ProjectTemplate')`, rerun your project and repost the errors and warnings please.

**Comment by Hugovdberg** [comment]
@sdrakulich Could you please tell us if the error still occurs and what warnings you see after installing the latest version from github?

**Comment by KentonWhite** [comment]
Haven't heard that the error still persists.  Closing for now.  If this error still is happening please reopen.
