### ISSUE TITLE
data.frames not converting to data.tables

### ISSUE THREAD

**Issue by UTexas80** [KentonWhite/ProjectTemplate#264]
#### Report an Issue / Request a Feature

I'm submitting a (Check one with "x") : 
- [ x] bug report 
- [ ] feature request

***

##### Issue Severity Classification - 

(Check one with "x") : 
- [ ] 1 - Severe
- [ x] 2 - Moderate
- [ ] 3 - Low

##### Expected Behavior

 Using the global.dcf in the configs folder, I  expect my data.frames which are defined in the data folder to be converted into data.tables

##### Current Behavior

 The data frames don't convert

##### Steps to Reproduce Behavior

 my global.dcf is set as follows

version: 0.8.2
data_loading: TRUE
data_loading_header: TRUE
data_ignore:
cache_loading: FALSE
recursive_loading: TRUE
munging: TRUE
logging: TRUE
logging_level: INFO
load_libraries: TRUE
libraries: BatchGetSymbols, caTools, curl, DataExplorer, data.table, devtools, dplyr, filesstrings,
            FinancialInstrument, foreach, fTrading, ggplot2, ggthemes, here, igraph, knitr, lubridate,
            modules, openxlsx, PerformanceAnalytics, plotly, plyr, Quandl, quantmod, quantstrat, readxl,
            reshape, reshape2, rio, rJava, rprojroot, skimr, SIT, SIT.date, stringr, tibble, tidyquant, timetk, TTR, xlsx, zoo
as_factors: FALSE
data_tables: TRUE
attach_internal_libraries: FALSE
cache_loaded_data: FALSE
sticky_variables: NONE

`insert short code snippets here`

library(tidyquant)                                                              # Loads tidyquant, tidyverse, lubridate, quantmod, TTR, and xts
library(TTR)                                                                    # Technical Trading Rules package
# SPL Processing --
SPL <- tq_get("SPL.AX")                                                         # Get SPL Stock Prices
SPL<-SPL[complete.cases(SPL),]                                                  # Delete NA
date <- SPL$date                                                                # Create date variable
key<-paste(as.character(format(date, "%Y")), as.character(format(date, "%m")), as.character(format(date, "%d")), "spl", sep = "")
# TTR Processing --
adx <- ADX(SPL[,c("high","low","close")])                                       # Welles Wilder’s ZLEMA is similar to an EMA, as it gives more weight to recent observations, but attempts to remove lag by subtracting data prior to (n-1)/2 periods (default) to minimize the cumulative effect.
# Create Table --
tblTrendADX <- data.frame(key,date,"spl",adx)                                   # Create Welles Wilder's ADX Table
 
##### Version Information

 
0.8.2

**Comment by KentonWhite** [comment]
Can you clarify something for me please?  When you say "data.frames which are defined in the data folder " do you mean that a data.frame is saved in the data folder as an RData file?  Or do you mean that an .R script in the data folder creates the data.frame?

**Comment by KentonWhite** [comment]
The flag `data_tables: TRUE` is for data structures that ProjectTemplate creates, like loading csv files or importing from a sql database.  When you run your own script in the data folder, the output is saved in the format created in the script.  So in your case, since the tblPrice is constructed as a data.frame, it will remain a data.frame — ProjectTemplate won't convert it.  If you need it as a data.table, you will need to convert it to a data.table from the script.

**Comment by UTexas80** [comment]
Thank you Kenton. Chalk it up to my newbie status. Live and learn.
Take care,
Glen
