### ISSUE TITLE
Test throws Errors if Context(file-name.R) not added

### ISSUE THREAD

**Issue by jflanaga** [KentonWhite/ProjectTemplate#265]
#### Report an Issue / Request a Feature

I'm submitting a (Check one with "x") : 
- [x ] bug report 
- [ ] feature request

***

##### Issue Severity Classification - 

(Check one with "x") : 
- [ ] 1 - Severe
- [ ] 2 - Moderate
- [x] 3 - Low

##### Expected Behavior

test.project() returns same information as `expect_that`. 

##### Current Behavior
test.project() returns `Error in x[[method]](...) : attempt to apply non-function`

```
✔ | OK F W S | Context
⠙ |  2       | 0Error in x[[method]](...) : attempt to apply non-function

══ Results ════════════════════════════════════════════════════════════════════════════════════════════
OK:       2
Failed:   3
Warnings: 0
Skipped:  0
```
##### Steps to Reproduce Behavior
Just run a test that fails

`expect_that(1+1, equals(3))`

 
##### Version Information
Latest version

##### Possible Solution
If you add `context(name_of_file)` before the tests, it works as expected. 

[This has been reported ](https://github.com/r-lib/testthat/issues/700) in `testthat`

**Comment by KentonWhite** [comment]
It looks like a proper `testthat` test should always start with `context()`.  What I can do here is modify the example `test/1.R` to include the context file.  Would that help?  I could add a global `context("ProjectTemplate")`, but this goes against the idea of `context()`, which is grouping tests together.  Do you have an opinion for why a global context would make sense?

**Comment by jflanaga** [comment]
I'm still trying to get my head around what a proper `testthat` test should look like, so I don't have an opinion about it. I think your initial proposal makes sense.

**Comment by Hugovdberg** [comment]
Perhaps a `context("Example tests")` would be better. This makes extra clear the file is initially just used for examples. People can always change it afterwards. The context `ProjectTemplate` suggests it contains tests for the actual `ProjectTemplate` functionality.

On a side note, `expect_that` is deprecated, you should use `expect_equal(1+1, 3)` in your case, or one of the other more explicit `expect_*` functions in other cases. The fallback should be `expect_true` or `expect_false` if none of the other functions suffice.

**Comment by KentonWhite** [comment]
Updated example test to use `testthat` best practices.
