### ISSUE TITLE
Suggestion for readme ni data folder

### ISSUE THREAD

**Issue by eribul** [KentonWhite/ProjectTemplate#267]
#### Report an Issue / Request a Feature

I'm submitting a (Check one with "x") : 
- [ ] bug report 
- [x] feature request

***

##### Issue Severity Classification - 

(Check one with "x") : 
- [ ] 1 - Severe
- [ ] 2 - Moderate
- [x] 3 - Low

##### Current Behavior

I always tend to forget how to specify the options in the .file that can be stored in the data folder (is it path or file, is it format or extension etc ...).
Therefore, I alwys have to visit http://projecttemplate.net/file_formats.html to check!
It might not be a big problem but it's just a little time consuming.

##### Version Information

0.82

##### Possible Solution

There is a readme-file in the data-folder with not so much info inside. 
My suggestion is to copy some info from the website to this readme file in order to always have it within reach!
Or at least a pointer to `?file.reader` etc where the info can also be found.

**Comment by KentonWhite** [comment]
@eribul Nice idea.  I've made the changes and should be on master soon.
