### ISSUE TITLE
Help: using projecttemplate  R within RStudio: Microsoft Azure Data Science VM

### ISSUE THREAD

**Issue by rsaavy** [KentonWhite/ProjectTemplate#278]
#### Report an Issue / Request a Feature

I'm submitting a (Check one with "x") : 
- [x] bug report 
- [ ] feature request

***

##### Issue Severity Classification - 

(Check one with "x") : 
- [x ] 1 - Severe
- [ ] 2 - Moderate
- [ ] 3 - Low

##### Current Behavior

I am just trying to get the project template starting thing to work but I am unable to get it to work.
##### Steps to Reproduce Behavior

Followed the tutorial up to  Load my project
> library('ProjectTemplate')
> create.project('letters')
> getwd()
[1] "C:/Users/RASAAVED/Documents/test"
> 

> setwd('~/letters/data/')
Error in setwd("~/letters/data/") : cannot change working directory
> setwd('~/letters/')
Error in setwd("~/letters/") : cannot change working directory
> setwd('/letters/')
Error in setwd("/letters/") : cannot change working directory
> setwd("~/test/letters/data")
> load.project()
Loading project configuration
Autoloading cache
Autoloading data
Munging data
Warning messages:
1: In .load.config(override.config) :
  You are missing a configuration file: config/global.dcf . Defaults will be used.
2: In .check.version(config) :
  Your configuration is compatible with version 0.5 of the ProjectTemplate package.
  Please run ProjectTemplate::migrate.project() to migrate to the installed version 0.7.
3: In .provide.directory("cache") : Creating missing directory cache
4: In .provide.directory("data") : Creating missing directory data
> 

 
##### Screenshots

![image](https://user-images.githubusercontent.com/18731785/45575740-a3c8d380-b842-11e8-9042-205c65a7ba28.png)
##### Version Information

Microsoft R Open 3.3.2
The enhanced R distribution from Microsoft
Microsoft packages Copyright (C) 2017 Microsoft
R version 3.3.2 (2016-10-31) -- "Sincere Pumpkin Patch"
Copyright (C) 2016 The R Foundation for Statistical Computing
Platform: x86_64-w64-mingw32/x64 (64-bit)

Loading Microsoft R Client packages, version 3.3.2.0033.

**Comment by Hugovdberg** [comment]
You shouldn't call `load.project` from within the data directory. Try `setwd('~/letters')` without the trailing slash, it's the only thing I can imagine why you couldn't change the directory (you didn't add the slash after data). If you really can't change the working directory to the root directory of the project then I cannot imagine it's a `ProjectTemplate` error but rather an Rstudio or Azure error.

**Comment by rsaavy** [comment]
thank you
