### ISSUE TITLE
Spelling - Main README.md

### ISSUE THREAD

**Issue by bugsysiegals** [KentonWhite/ProjectTemplate#279]
#### Report an Issue / Request a Feature

I'm submitting a (Check one with "x") : 
- [ X] bug report 
- [ ] feature request

***

##### Issue Severity Classification - 

(Check one with "x") : 
- [ ] 1 - Severe
- [ ] 2 - Moderate
- [X ] 3 - Low

##### Expected Behavior

* Loading any R packages you listed in the configuration file.

##### Current Behavior

* Loading any R packages you listed in he configuration file.

##### Steps to Reproduce Behavior

`insert short code snippets here`

**Comment by KentonWhite** [comment]
Thanks @bugsysiegals  We'll make the correction soon.  If you would like, you could make a pull request with the correction made.  Let me know if you'd like some help making a pull request!

**Comment by bugsysiegals** [comment]
No problem.  Unfortunately I'm a newbie to GIT and am not sure how to do that for you but would be happy to if you can explain.  

BTW, thanks for all the time you've put into this!!  Do you have some sort of messenger I could ping you about a few questions I have?

**Comment by KentonWhite** [comment]
Working on correcting documents is a great way to start!  On the GitHub website, find the file where the error is (you could probably use the search feature).  Once there, click on the edit link (this is a little pencil icon in the upper right corner).  Make your changes and fill in at the bottom what the change was (like, corrected spelling mistake).  This will create a fork in your account.  Then you can click on the Pull Request menu.  GitHub should walk you through creating a Pull Request.

You can learn more about the Pull Request process [here](https://help.github.com/articles/about-pull-requests/)

**Comment by bugsysiegals** [comment]
Looks like you merged one of the README.md files ... there's 1 from each template.  Will close this issue as soon as the other is merged.
