### ISSUE TITLE
Missing spaces in warning

### ISSUE THREAD

**Issue by eribul** [KentonWhite/ProjectTemplate#295]
Just missing some spaces in a warning.

Current:

```r
Warning message:
In .require.package("digest") :
  Loading librarydigestinto workspace as a side effect of loading data.
  Normally, there is no need to attach a package for this purpose.
  To turn off this warning, change the "attach_internal_libraries" setting in your
  configuration to FALSE.
```

Hence "librarydigestinto" should probably be "library digest into" (perhaps a use of `paste` instead of `paste0` or similar)

**Comment by Hugovdberg** [comment]
This is probably because the `...` argument to `warning` takes "zero or more objects which can be coerced to character (and which are pasted together with no separator) or a single condition object.". The leading and trailing text should therefore end and start with a space.
