### ISSUE TITLE
quite/verbose option in `run.project`

### ISSUE THREAD

**Issue by eribul** [KentonWhite/ProjectTemplate#298]
#### Report an Issue / Request a Feature

I'm submitting a (Check one with "x") : 
- [ ] bug report 
- [x] feature request

***

##### Issue Severity Classification - 

(Check one with "x") : 
- [ ] 1 - Severe
- [ ] 2 - Moderate
- [x] 3 - Low

##### Expected Behavior

I have a lot of files in `/src`.
When I run them all (`run.project`) the output gets very messy since the same information repeats from `load.project` in every file.
Therefore, I usually start my scripts with `suppressMessages({library(ProjectTemplate); load.project()})`

It would be nice however if I could omit `suppressMessages` here. It is sometimes nice to get the output when running individual script files. 
But then it would be nice to have an argument like "quiet" or "verbose" to use in `run.project` for the same behanviour.

##### Current Behavior
A lot of output that is hard to grasp.

##### Steps to Reproduce Behavior

`run.project()`

##### Version Information
R: 3.6.1
ProjectTemplate: 0.9.0

**Comment by KentonWhite** [comment]
I think we looked at implementing quiet messages before — I can't really recall.  I'll put this into the queue to look at and see if it is possible.
