### ISSUE TITLE
Support underscore in data file names

### ISSUE THREAD

**Issue by lyh970817** [KentonWhite/ProjectTemplate#301]
#### Report an Issue / Request a Feature

I'm submitting a (Check one with "x") : 
- [ ] bug report 
- [x] feature request

***

##### Issue Severity Classification - 

(Check one with "x") : 
- [ ] 1 - Severe
- [ ] 2 - Moderate
- [x] 3 - Low

##### Expected Behavior

when data files in the 'data' folder have names in underscore (e.g. dat_raw) the loaded data frame should have identical names to the file.

##### Current Behavior

When loading a file named 'dat_raw', the loaded data frame is named as 'dat.raw'.

##### Steps to Reproduce Behavior

* Create a data file in the 'data' folder named 'dat_raw.rds'

* `setwd` to the project directory and call `load.project`.

##### Version Information

* R version 3.6.3
* ProjectTemplate_0.9.1

**Comment by KentonWhite** [comment]
Should be straightforward.  I'll work on it this weekend.

**Comment by lyh970817** [comment]
> Should be straightforward. I'll work on it this weekend.

Thank you so much!

**Comment by KentonWhite** [comment]
This has been added.  You can check it out in in PR.  It will take about a week for this to show up on CRAN. There is a config var underscore_variables that can be set to TRUE.   New projects will default to TRUE.  Old projects when migrated will go to FALSE so that we don't break projects.
