### ISSUE TITLE
Let `cache()` return a value

### ISSUE THREAD

**Issue by ImperialSquid** [KentonWhite/ProjectTemplate#316]
#### Report an Issue / Request a Feature

I'm submitting a (Check one with "x") : 
- [ ] bug report 
- [x] feature request

***

##### Issue Severity Classification - 

(Check one with "x") : 
- [ ] 1 - Severe
- [ ] 2 - Moderate
- [x] 3 - Low

##### Expected Behavior

It would be nice to have `cache()` return `TRUE`/`FALSE` for whether it performed an update/skipped caching due to the cache being up to date.

I'm working on a project where a lot of downstream work depends on values updated from online. When loading the project, it would be nice to know if my caches are out of date compared to those remote values or if I need to recompute anything.

##### Current Behavior

`cache()` has no return value.

##### Steps to Reproduce Behavior

N/A, but here's how I would use this feature

```
foo = <some semi unstable values>

updated = cache(foo)

if (updated) {
    bar = <more complex recomputation>
} else {
    cat("Cache up to date with remote value, skipping...\n")
}
```
 
##### Screenshots

N/A

##### Version Information

R: 4.2.2
RStudio: 2024.09.1+394 "Cranberry Hibiscus"
ProjectTemplate: 0.11.0

##### Possible Solution

ProjectTemplate clearly knows when an update happens since it changes the output message depending, it would just mean returning that information to the user too

**Comment by KentonWhite** [comment]
Hi,

Thanks for the use case.   I really appreciate how returning a Boolean could help in this particular case.   If you look at `R/cache.R` there are more than 2 possible states for cache to return:

- The variable doesn't exist in the global environment or doesn't have code to cache it
- The variable was cached from the global environment
- The variable was cached from the code
- The variable was not able to be updated
- Skipping caching because the variable is already up-to-date
- Updating the variable

Rather than providing different return values, we use messages to communicate.  The nice thing about messages is that you can handle them in a very similar way to handling errors.  So you can define specific code for each message that you encounter.

Here is a good description of [handling conditions](https://adv-r.hadley.nz/conditions.html), including how to handle messages.

Please let me know if this helps you catch the cases where you wish to do the more complicated re-computation.

**Comment by ImperialSquid** [comment]
Ah gotcha, that's very useful (and as the docs point out, definitely different from how most languages do errors/etc!)

So in my case, I'd want something roughly equivalent to: 

```
updated = withCallingHandlers(
    message = function(cnd) {
        if(! grepl("Skipping", conditionMessage(cnd))) {
            # if we're here, updated = True, otherwise, False
        }
    },
    cache(foo)
)
```

(Since in my use case, caching when it doesn't exist already and updating the cache both mean I need to do the latest recomputations. But other use cases might have to modify that message catching function.)

---

Do you have any advice on getting the updated values out of the message handler? (Since I presume it won't write to the correct scope if I assign it there). 

Section 8.6.2 has information about return values but only uses `tryCatch` in it's examples. I could throw an error when I get inside the if statement, but I don't know if that would abort the whole caching process since the `message` lines are above the `cache`-ing lines in `R/cache.R`...

**Comment by KentonWhite** [comment]
That is very old school Unix!

Any work you do in the message handler should be in the proper scope.   The difference is that `withCallingHandlers()` returns context back into where the message was called.  I think this is the behaviour you want — you are inserting the additional update just before the cache is updated.  

Maybe I misunderstood and you want to do additional computation after the cache is updated.  If that is the case, then just cache `bar` with a depends on `foo`:

```
cache("foo")
cache("bar", depends=c("foo"))
```

Then` bar` will only be updated if `foo` is updated.  If `foo` wasn't updated then `bar` won't update!

**Comment by ImperialSquid** [comment]
Lol, yeah I guess it is at that!

---

I'm not sure if there's been a mismatch in communication, but it's not behaving for me. [Here](https://github.com/ImperialSquid/BFI_BoxOffice/blob/91199a4aa49ab8663021dedc70996424267fa177/bfi_boxoffice/data/01_get_spreadsheet_links.R#L51-L60)'s a link to the actual script so you can see everything I'm doing (and where I'm probably going wrong!).

(The `updated` variable is then used in later scripts in the `/data` folder that do the more intense computation, then it gets removed (and uncached) in a clean-up script so it won't interfere if I reload the project.)

If I don't use `assign(... envir = .GlobalEnv)`, the value doesn't get set properly (even if I do something like declaring it in global scope first and then set it inside `withCallingHandlers`)...

---

The `depends` parameter is useful, but not quite what I'm looking for. Since that still requires that you do the computation for `bar` whether or not you end up caching it, which is the step I'm trying to skip... Good to know that exists for the future, though!

**Comment by KentonWhite** [comment]
When you say it is not behaving properly, is it that the handlers aren't being called?

BTW, we have to use the .GlobalEnv all over the place in ProjectTemplate.  It is the only way :(

**Comment by ImperialSquid** [comment]
The handlers get called fine, it's just that I can't get the value of `updated` out with using `assign(..., envir = .GlobalEnv)`... 🤷‍♂️ 

(I feel a bit gross assigning to global like this so forcefully, it feels like a code smell lol... But if you say it's the only way, I'm happy to leave it be like that!)

---

I'm happy for you to close this issue, unless you do want to add the `cache()` return value stuff in future. 

But I've got all the functionality I was looking for. Thanks for pointing me towards the message handlers functionality, it was very useful! 😁
