### ISSUE TITLE
What happens if a dataset is named options or project.info?

### ISSUE THREAD

**Issue by krlmlr** [KentonWhite/ProjectTemplate#66]
Test, possibly fix, document.

**Comment by Hugovdberg** [comment]
I'm guessing `options` has been changed to `config` in the meantime. At the moment, `project.info` is the only variable assigned in the global environment *after* the data is loaded, without checking if any variable with that name already exists. The other two are assigned earlier and so a conflicting file will be skipped while loading as the variable is considered to be loaded already. In either case the three variables always supersede a conflicting dataset. I'm not sure this is documented as such already.
To prevent this behaviour from changing unintentionally we could perhaps rename them to `.config`, `.project.info` and `.logger`? Filenames starting with a dot are ignored on all platforms by `list.files`, so these files will not be loaded and thus don't have the potential to overwrite, or be overwritten by, these variables.

**Comment by KentonWhite** [comment]
Good idea. Will this be part of #187?

**Comment by Hugovdberg** [comment]
I don't think we should add more feature changes to #187 at the moment. Renaming these variables is definitely breaking backwards compatibility, and should be changed in all relevant tests. If no tests exist for these variables, they should be created, so altogether I think we should do this in a separate PR. 
I also noticed (so far it is unchanged) that the loaded configuration is both in `config` and in `project.info$config`. Are there compelling reasons to keep both or should we remove one of the two?

**Comment by KentonWhite** [comment]
I'm not sure.  I'll have to dig into the code to answer that. Good question!

**Comment by KentonWhite** [comment]
I'm closing this for now.  Please re-open if we need to continue this discussion!
