### ISSUE TITLE
Provide an easy way to invalidate cache

### ISSUE THREAD

**Issue by krlmlr** [KentonWhite/ProjectTemplate#80]
Currently, file has to be removed manually from `cache` subdirectory. Can we do better?

```
invalidate.cache <- function(names = NULL) { ... }
```

Or even a config option?

**Comment by connectedblue** [comment]
My proposal #152 contains a function to clear the cache of one or more objects:
`clear.cache(c("foo", "bar")`
will delete those variables from the cache if they exist.

It provides an interface and a simple implementation behind (just deleting the correct files from the cache directory).  If more advanced stuff comes along such as cache aging, maybe this interface could be extended to incorporate those?
